# Generated by Django 5.0.1 on 2024-01-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='descripción',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='web_page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
