# Generated by Django 5.0.1 on 2024-01-26 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('sub_title', models.CharField(max_length=140)),
                ('content', models.TextField(max_length=500)),
                ('date', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, default='blog/images/default.jpg', null=True, upload_to='blog/images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
